### ISSUE TITLE
Add world phone support

### ISSUE THREAD

**Issue by deadman96385** [sultanqasim/android_device_htc_pme#1]
Not sure the best way to contact you so i'll leave this here. I am currently working on proper world phone support. The main amount of the work is writing the init file which i am almost done doing you can see it [here](https://github.com/deadman96385/android_device_htc_pme/commit/1b41ec8fd13396bfa32b05f34e89e952459e9a2d).

What i have left to do is the following:
- Add the following cid variant props VZW__001, SPCS_001, HTC__621, O2___102 (Currently they are generic)
- Figure out how to handle US unlocked models (They do not set ril props via customize)
- Add the following GSM prop values to all cid variants

```
ro.ril.fd.pre_r8_tout.scr_on
ro.ril.fd.pre_r8_tout.scr_off
ro.ril.fd.r8_tout.scr_on
ro.ril.fd.r8_tout.scr_off
ro.ril.radio.svn
ro.ril.ltefgi
ro.ril.ltefgi.rel9
ro.ril.ltefgi.rel10
ro.ril.disable.sync_pf
ro.ril.hsdpa.dbdc
```

**Comment by sultanqasim** [comment]
Thanks for getting started on this. What you're doing is essentially what I had in mind. I first need to get the RIL up and running, and then we can finish up this regional variant configuration.

**Comment by deadman96385** [comment]
:) Cool yeah i thought i may as well work on it because i know how to write that part. I'll let you know when its finalized with at least all of the variant cids and, cid specific props.

**Comment by deadman96385** [comment]
All cid's are added except for the US Unlocked variants because i am not sure how to handle them yet because they do not set ril props via customize partiton. Other then that they are good to go https://github.com/deadman96385/android_device_htc_pme/commit/39ad14394d31e77ec7121060cd8c4db70c9274c1

**Comment by deadman96385** [comment]
Here are all of the customize partitions that i used to get the ril props for each of the cid variants in each folder go under clientid and you will see the xml's.

https://goo.gl/uU9d71

**Comment by deadman96385** [comment]
Merged :+1:
